### ISSUE TITLE
Any examples for the code?

### ISSUE THREAD

**Issue by vancky** [EllissoideRotondo/mexspice#1]
It seems the code has cleaned up and the generate_mex.m cannot run correctly.

Any idea to speed up the querying the position of the planets using spkezr in matlab?

Thanks.

**Comment by EllissoideRotondo** [comment]
Apologies for that, I haven't updated this repo in some time.
I made some changes to the code and I pushed an example that shows how to use the interface, let me know if it works for you.
To answer your question: to speed up querying the ephemerides, you can use the lower-level interface spkgps (for position only) or spkgeo (for position-velocity). This should be slightly faster than using spkezr. You can find more info about this here: https://degenerateconic.com/speeding-up-spice.html
Thanks!

**Comment by vancky** [comment]
Thanks for your reply.
The new script example_1.m can work, and the speed is extremely fast (1.1s vs 0.11s for 10 years integrate). What is the reason for this?  The speed to query the positions or ode89 in mex mode? 

And could you fix the run_test.m and the generate_mex.m to just test the speed of cspice_spkezr  vs the  mex version of this function (just like spkezr_c in run_test.m)?

Thanks!

**Comment by EllissoideRotondo** [comment]
The speed-up is due to transforming the ode89 call to a MEX file. To achieve the full potential of MEX, the calls to cspice need to happen within the C file (rather than doing a call through the Matlab engine, which is what MICE does), which is why I wrote this code.
I'll work on fixing the code tomorrow, but I can already tell you that the speed between cspice_spekzr vs my own mex (when using them on their own, as opposed to the ode example above) is going to be negligible).

**Comment by vancky** [comment]
Thanks very much!
